# This docker compose is the exact same as option 1, however our backend image is more traditional, using PHP-FPM and Caddy instead of Swoole.
# The downside being a bit of added complexity with multiple more processes and needing to use something like supervisord to wrangle them up.
# The upside being that its a lot more traditional, supported, documented, and we can rely on the official php image instead of the Swoole one.
services:
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./public/:/sites
      - ./build/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - main
      - vendors
      - caddy
  backend:
    build:
      context: .
      dockerfile: build/option4/Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-fI", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    networks:
      - main
  mailhog:
    image: mailhog/mailhog:latest
    environment:
      MH_HOSTNAME: mail.test
      MH_MAILDIR_PATH: /data
      MH_STORAGE: maildir
    user: 0:0
    ports:
      - "8025:8025"
    volumes:
      - mailhog:/data
    networks:
      - vendors
volumes:
  caddy_data:
  caddy_config:
  mailhog:
networks:
  main:
    driver: bridge
  vendors:
    driver: bridge
  caddy:
    driver: bridge
