# This docker compose gives a less explicit view into which static assets are being served by having all sites served through the /sites folder.
# This can be a little confusing at first glance yet allows us to deploy new sites by just changing the caddy file and reloading caddy.
services:
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./public/:/sites
      - ./build/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - main
      - vendors
      - cadidy
  backend:
    build:
      context: .
      dockerfile: build/backend.Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-fI", "http://localhost:8080"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    networks:
      - main
  mailhog:
    image: mailhog/mailhog:latest
    environment:
      MH_HOSTNAME: mail.test
      MH_MAILDIR_PATH: /data
      MH_STORAGE: maildir
    user: 0:0
    ports:
      - "8025:8025"
    volumes:
      - mailhog:/data
    networks:
      - vendors
volumes:
  caddy_data:
  caddy_config:
  mailhog:
networks:
  main:
    driver: bridge
  vendors:
    driver: bridge
  cadidy:
    driver: bridge
