# This docker compose gives a more explicit view into which static assets are being served by having each one be in its own volume.
# The downside being needing to redeploy the stack whenever we want to add any new sites
services:
  caddy:
    image: caddy:2.8.4-alpine
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./public/main:/sites/main
      - ./public/prototype:/sites/prototype
      - ./public/docs:/sites/docs
      - ./build/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - main
      - vendors
      - caddy
  backend:
    build:
      context: .
      dockerfile: build/backend.Dockerfile
    healthcheck:
      test: ["CMD", "curl", "-fI", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    networks:
      - main
  mailhog:
    image: mailhog/mailhog:latest
    environment:
      MH_HOSTNAME: mail.test
      MH_MAILDIR_PATH: /data
      MH_STORAGE: maildir
    user: 0:0
    ports:
      - "8025:8025"
    volumes:
      - mailhog:/data
    networks:
      - vendors
volumes:
  caddy_data:
  caddy_config:
  mailhog:
networks:
  main:
    driver: bridge
  vendors:
    driver: bridge
  caddy:
    driver: bridge
